# Uncomment the next line to define a global platform for your project
# platform :OS X, '10.9'

target 'AESEnDeCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AESEnDeCode
	pod 'AFNetworking', '~> 3.0'


  target 'AESEnDeCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AESEnDeCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
